set.seed(234)

require(semtree)

N <- 200
err <- sqrt(.1)

z <- rnorm(N)  

# simulate CFA
lat <- rnorm(N)+ifelse(z>0,1,0)+ifelse(z>0.5,3,0)
loadings <- c(.5,.7,.9,.3)
obs <- t(matrix(loadings) %*% t(lat)) + rnorm(N*length(loadings),0,err)


modelData <- data.frame( obs)
modelData$zz <- z
names(modelData) <- c(paste0("x",1:4),"z")

# omx model
#
# This model specification was automatically generated by Onyx
# 
require("OpenMx");
manifests<-c("x2","x3","x1","x4")
latents<-c("YY")
model <- mxModel("Unnamed_Model", 
                 type="RAM",
                 manifestVars = manifests,
                 latentVars = latents,
                 mxPath(from="YY",to=c("x2","x3","x1","x4"), free=c(TRUE,TRUE,TRUE,TRUE), value=c(0.0,0.0,0.1,.5) , arrows=1, label=c("YY__x2","YY__x3","YY__x1","YY__x4") ),
                 mxPath(from="YY",to=c("YY"), free=c(FALSE), value=c(1.0) , arrows=2, label=c("VAR_YY") ),
                 mxPath(from="x2",to=c("x2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x2") ),
                 mxPath(from="x3",to=c("x3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x3") ),
                 mxPath(from="x1",to=c("x1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x1") ),

                 mxPath(from="x4",to=c("x4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x4") ),
                 mxPath(from="one",to=c("x2","x3","x1","x4","YY"), free=c(F,F,F,F,T), 
                        value=0, arrows=1,label=c("m2","m3","m1","m4","mYY")),
                 mxData(modelData, type = "raw")
);

result <- mxRun(model)
summary(result)

omxGetParameters(result)
# create SEM tree

ctrl <- semtree.control(test.type="score",method = "naive",verbose=TRUE)
ctrl$min.bucket<-0
tree <- semtree(model = result, dat=modelData,control = ctrl)

plot(tree)